import { useMemo, useState } from 'react'
import { Camera, Check, ChevronLeft, Clock3, Headphones, MapPin, Menu, Phone, ShieldCheck, Sparkles, Star, X } from 'lucide-react'
import { cases, categories, places } from './data/cases'

function App(){
  const [active, setActive] = useState(0), [score,setScore]=useState(0), [streak,setStreak]=useState(0), [answered,setAnswered]=useState<number|null>(null), [filter,setFilter]=useState('הכול'), [menu,setMenu]=useState(false)
  const filtered = useMemo(()=>filter==='הכול'?cases:cases.filter(c=>c.category===filter),[filter])
  const current = filtered[active%filtered.length]
  const choose=(correct:boolean)=>{ if(answered!==null)return; setAnswered(correct?1:0); setScore(s=>s+(correct?100:20)); setStreak(s=>correct?s+1:0) }
  const next=()=>{setAnswered(null);setActive(a=>a+1)}
  return <div className="app">
    <header className="topbar"><div className="brand"><span className="brand-mark"><ShieldCheck size={25}/></span><div><strong>גיבורי המוקד</strong><small>מרכז המשימות של השכונה</small></div></div><div className="top-actions"><div className="live"><span/> המוקד פעיל</div><button className="icon-btn" aria-label="פתיחת תפריט" onClick={()=>setMenu(!menu)}><Menu/></button><div className="avatar">נ</div></div></header>
    {menu&&<div className="mobile-menu"><b>שלום, נועה 👋</b><span>היום במשמרת: 12 משימות</span></div>}
    <main>
      <section className="hero"><div><p className="eyebrow"><Sparkles size={15}/> משמרת חדשה מחכה לך</p><h1>עיניים חדות.<br/><em>לב גדול.</em></h1><p className="intro">עוזרים לשכונה הדמיונית שלנו, משימה אחת בכל פעם. מקשיבים, בוחרים נכון ולומדים לשמור על כולם.</p><div className="hero-meta"><span><Star size={16} fill="currentColor"/> {score.toLocaleString()} נקודות</span><span><span className="streak-dot"/> רצף {streak}</span><span><Clock3 size={16}/> זמן משחק רגוע</span></div></div><div className="hero-art"><div className="sun"/><div className="city"><i/><i/><i/><i/><i/></div><div className="hero-card"><span>משימה #{String(current.id).padStart(2,'0')}</span><b>הגיע דיווח חדש</b><small>{current.location} · {current.time}</small></div></div></section>
      <div className="section-heading"><div><p className="eyebrow">לוח המוקד</p><h2>מה קורה בשכונה?</h2></div><button className="outline-btn"><Headphones size={17}/> הסבר קולי</button></div>
      <section className="dashboard-grid">
        <article className="panel calls"><div className="panel-head"><div><span className="live-label"><span/> נכנס עכשיו</span><h3>תור דיווחים</h3></div><span className="count">{cases.length}</span></div><div className="call-list">{cases.slice(0,4).map((c,i)=><button className={`call-row ${i===0?'selected':''}`} key={c.id} onClick={()=>{setActive(i);setAnswered(null)}}><span className="call-icon" style={{background:c.color}}><Phone size={16}/></span><span><b>{c.title}</b><small><MapPin size={12}/>{c.location}</small></span><span className="call-time">{i===0?'עכשיו':`${i*3} ד׳`}</span></button>)}</div><button className="text-btn">לכל הדיווחים <ChevronLeft size={16}/></button></article>
        <article className="panel cameras"><div className="panel-head"><div><span className="live-label"><span/> מצלמות חיות</span><h3>קיר השכונה</h3></div><Camera size={20}/></div><div className="camera-grid">{places.slice(0,4).map((p,i)=><div className="camera-tile" key={p}><div className={`cam-scene scene-${i}`}><span className="scanline"/><span className="cam-label"><span/> REC · {p}</span><span className="scene-object">{['☀','🌳','🚲','☂'][i]}</span></div></div>)}</div><div className="camera-footer"><span>4 מתוך 8 מצלמות פעילות</span><button className="text-btn">לצפייה מלאה <ChevronLeft size={16}/></button></div></article>
      </section>
      <section className="mission"><div className="mission-top"><div><p className="eyebrow">החלטה שלך</p><h2>מה עושים עכשיו?</h2></div><div className="mission-number"><span>דיווח</span><b>#{String(current.id).padStart(2,'0')}</b></div></div><div className="mission-body"><div className="case-illustration" style={{background:current.color}}><div className="case-sun"/><div className="case-building"/><div className="case-sticker">🔎</div><small>איור המחשה בטוח</small></div><div className="case-content"><div className="case-tags"><span>{current.category}</span><span><MapPin size={13}/>{current.location}</span></div><h3>{current.title}</h3><p className="clue">“{current.clue} — מה הבחירה הכי טובה שלך?”</p><div className="choices">{current.choices.map((choice,i)=><button key={choice.label} className={`choice ${answered!==null?(choice.correct?'right':i===0?'wrong':'muted'):''}`} onClick={()=>choose(choice.correct)}><span className="choice-key">{['א','ב','ג'][i]}</span><span>{choice.label}</span>{answered!==null&&choice.correct&&<Check size={18}/>}</button>)}</div>{answered!==null&&<div className={`feedback ${answered?'success':'try'}`}><span>{answered?<Check size={17}/>:<X size={17}/>}</span><b>{answered?'בחירה מצוינת!':'כמעט!'}</b> {current.choices[answered?0:1].feedback}<button onClick={next}>למשימה הבאה <ChevronLeft size={15}/></button></div>}</div></div><div className="safety"><ShieldCheck size={17}/><span><b>זוכרים:</b> במשחק ובחיים האמיתיים משתפים מבוגר שסומכים עליו. במקרה חירום אמיתי פונים לשירותי החירום.</span></div></section>
      <div className="section-heading filters"><div><p className="eyebrow">ספר המשימות</p><h2>עוד סיפורים מהשכונה</h2></div><div className="filter-tabs">{['הכול',...categories].map(f=><button className={filter===f?'active':''} onClick={()=>{setFilter(f);setActive(0)}} key={f}>{f}</button>)}</div></div><div className="case-strip">{filtered.slice(0,6).map(c=><button className="mini-case" key={c.id} onClick={()=>{setActive(filtered.indexOf(c));setAnswered(null)}}><span style={{background:c.color}}>{c.title.slice(0,1)}</span><b>{c.title}</b><small>{c.location}</small></button>)}</div>
    </main><footer><span>גיבורי המוקד · משחק דמיוני ללמידה ולכיף</span><span>אין כאן תחליף לעזרה אמיתית של מבוגר או שירותי חירום</span></footer>
  </div>
}
export default App
